---

- name: "Check Platform "
  hosts: all
  connection: paramiko
  vars:
#       ansible_ssh_user: "{{ usrR }}"
#       ansible_ssh_pass: "{{ passR }}"
#       http_port: 80
#       domain: example.com
    ansible_paramiko_user: "{{ usrR }}"
    ansible_paramiko_pass: "{{ passR }}"
#      ansible_ssh_private_key_file: /path/to/private_key
#      ansible_ssh_pass: passphrase_for_private_key
  tasks:

    - name: "iRedMail on Cent OS 7"
      include_tasks: "CentOS/iRedmailcos7.yml"
      when: ansible_distribution == 'CentOS'  and ansible_distribution_major_version == "7" or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: "Debian 9"
      include_tasks: "Debian/iRedmailD9.yml"
      when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch' and ansible_distribution_major_version == '9'
