---

- name: "Platform Independ test"
  hosts: all
  connection: paramiko
  vars:
      ansible_ssh_user: "{{ usrR }}"
      ansible_ssh_pass: "{{ passR }}"
#     ansible_paramiko_user: "{{ usrR }}"
#     ansible_paramiko_pass: "{{ passR }}"
#      ansible_ssh_private_key_file: /path/to/private_key
#      ansible_ssh_pass: passphrase_for_private_key
  tasks:
    - command: echo "CentOS or RHEL"
    - debug:
        msg: "CentOS or RHEL"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - command: echo "Debian or Ubuntu"
    - debug:
        msg: "Ubuntu or Debian"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


###  Important!!! #################
## when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
##       (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
## ansible-playbook -i 176.32.195.91,  --extra-vars 'usrR=root passR=PmbNVj3Rkuhb' platform.yml
#- set_fact:
#  destination: "/etc/nagios/nrpe.d/"
#  when: ansible_os_family == "Debian"

#- set_fact:
#  destination: "/etc/nrpe.d/"
#  when: ansible_os_family == "RedHat"
##########################################

