---
- hosts: ovdslave
  remote_user: ovduser
  sudo_user: ovduser
  sudo: yes
  tasks:     
   - name: Run the equivalent of "apt-get update" as a separate step   
     apt:
        update_cache: yes
        upgrade: dist
   - shell: echo "Upgrade Complete"
     register: out
   - debug: var=out.stdout_lines
