---

- name: "Check Platform "
  hosts: all
  connection: paramiko
  vars:
#       ansible_ssh_user: "{{ usrR }}"
#       ansible_ssh_pass: "{{ passR }}"
#       http_port: 80
#       domain: example.com
    ansible_paramiko_user: "{{ usrR }}"
    ansible_paramiko_pass: "{{ passR }}"
#      ansible_ssh_private_key_file: /path/to/private_key
#      ansible_ssh_pass: passphrase_for_private_key
  tasks:

    - name: "Zimbra on Cent OS 7"
      include_tasks: "CentOS/zimbracos7.yml"
      when: ansible_distribution == 'CentOS'  and ansible_distribution_major_version == "7" or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: "Zimbra on Ubuntu 14"
      include_tasks: "Ubuntu/zimbrau14.yml" 
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' and ansible_distribution_version == '14.04'

#    - command: echo "openSUSE Leap"
#    - debug:
#        msg: "openSUSE Leap {{ ansible_distribution_version }} "
#      when: ansible_distribution == 'openSUSE Leap' and ansible_distribution_version == "42.2"
